version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nyimbi-lambda-task-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1d1geouqy1m97"
s3_prefix = "nyimbi-lambda-task-1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
