AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Nyimbi AWS Lambda Badge - Task 1 - Queue Processor
  Using SAM Template

Globals:
  Function:
    Timeout: 3

Resources:
  NyimbiINQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 'NyimbiINQueue'

  NyimbiSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        # Subscription takes a list of subscriptions
        -
          Endpoint: 'nyimbi.odero@devfactory.com'
          Protocol: 'email'

      TopicName: 'NyimbiSNSTopic'
      DisplayName: 'FlaggedWordsTopic'

  PublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sns_publisher/
      Handler: app.lambda_handler
      Runtime: python3.9
      Description: 'Consumes SQS messages and publishes to an SNS Topic'
      Events:
        SQSIncoming:
          Type: SQS
          Properties:
            Queue: !Join [':', [!GetAtt 'NyimbiINQueue.Arn']]
            BatchSize: 1

      Policies:
        - SNSPublishMessagePolicy:
            TopicName: 'NyimbiSNSTopic'
        - SQSPollerPolicy:
            QueueName: 'NyimbiINQueue'
        - LambdaInvokePolicy:
            FunctionName: 'PublisherFunction'
        - SNSCrudPolicy:
            TopicName: 'NyimbiSNSTopic'


      Environment:
        Variables:
          INQUEUE: !Ref 'NyimbiINQueue'
          MAXMSG: 1
          SNSTOPIC: !Ref 'NyimbiSNSTopic'

Outputs:
  PublisherFunction:
    Description: "PublisherFunction Lambda Function ARN"
    Value: !GetAtt PublisherFunction.Arn

  PublisherFunctionIamRole:
    Description: "Implicit IAM Role created for PublisherFunction function"
    Value: !GetAtt PublisherFunctionRole.Arn

  QueueURL:
    Description: 'URL of the SQS Queue that receives the push notifications.'
    Value: !Ref 'NyimbiINQueue'

  QueueARN:
    Description: 'ARN of the SQS Queue that receives the push notifications.'
    Value: !Join [':', [!GetAtt 'NyimbiINQueue.Arn']]

  QueueName:
    Description: 'Name of the SQS Queue that receives the push notifications.'
    Value: !Join [':', [!GetAtt 'NyimbiINQueue.QueueName']]

